project:
  type: book
  output-dir: docs

book:
  title: Open Research
  sidebar: 
    logo: "https://forrt.org/img/FORRT.svg"
    background: "#FEFDF6"
    foreground: "#800080"
  issue-url: https://github.com/forrtproject/Open-Research-course/issues
  repo-url: https://github.com/forrtproject/Open-Research-course
  repo-actions: [issue, edit]
  chapters:
  - part: Overview
    chapters: 
    - index.qmd
  - part: Chapters
    chapters:
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
  - part: Appendices
    chapters:
    - glossary.qmd
    - reference.qmd
format:
  html:
    theme: cosmo
    page-layout: full
    css: 
    - styles.css
    - include/webex.css
    include-after-body: 
    - include/webex.js
    linestretch: 1.75
editor: source
toc: true
toc-depth: 4
include-after-body: "footer.html"
from: markdown+emoji
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "assets/forrt_icon.png" />
  - text: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
custom-callout:
  yellow: 
    color: "#86754a"
    icon-symbol: "fa-info-circle"
  red:
    color: "#8e0000"
  green: 
    color: "#bad6c2"
    icon-symbol: "fa-lightbulb"
  caution: 
    color: "#ff9a00"
    icon-symbol: "fa-warning"
filters:
- custom-callout
popover-glossary:
  path: glossary.yml
